Repository Strnadi/Strnadi-Mobile-App, pull requests merged in 2025-03, with the labels that each got.

#57 mapy.cz add and grid fix
  .dart_tool/version
  assets/map.html
  lib/AudioSpectogram/editor.dart
  lib/PostRecordingForm/RecordingForm.dart
  lib/bottomBar.dart
  lib/main.dart
  lib/map/map.dart
  lib/map/mapv2.dart
  lib/recording/streamRec.dart
  lib/user/userPage.dart
  pubspec.yaml
Labels: enhancement

#75 redesign and wip
  lib/recording/streamRec.dart
Labels: enhancement

#88 feat: Register redesign and photo upload at PostRecordingForm
  lib/auth/registeration/mail.dart
  lib/auth/registeration/mailSent.dart
  lib/auth/registeration/nameReg.dart
  lib/auth/registeration/passwordReg.dart
  lib/localRecordings/recordingsDb.dart
  lib/locationService.dart
  lib/user/settingsManager.dart
  lib/user/settingsPages/appSettings.dart
Labels: enhancement

#89 feat: discard recording button and spectogram computation in background
  lib/PostRecordingForm/RecordingForm.dart
  lib/PostRecordingForm/imageUpload.dart
  lib/auth/forgottenPassword.dart
  lib/auth/login.dart
  lib/auth/registeration/passwordReg.dart
  lib/localRecordings/recordingsDb.dart
  lib/recording/streamRec.dart
  lib/widgets/spectogram_painter.dart
  pubspec.yaml
Labels: bug, enhancement

#122 feat: postRecordingForm changes and map fixes
  lib/localRecordings/recListItem.dart
  lib/map/mapv2.dart
  lib/map/searchBar.dart
  lib/recording/streamRec.dart
Labels: bug, enhancement

#133 Licence add
  lib/PostRecordingForm/RecordingForm.dart
  lib/auth/registeration/mail.dart
  lib/callback_dispatcher.dart
  lib/localRecordings/recList.dart
  lib/localRecordings/recListItem.dart
  lib/map/searchBar.dart
  lib/notificationPage/notifList.dart
  lib/notificationPage/notifications.dart
  lib/recording/streamRec.dart
  lib/recording/waw.dart
Labels: licnce
